#!/bin/sh
#
#   Set screen resolution with xrandr at xmde start.
#   This should be called by the xmde rc file.
#

# Launch the xrandr probe and set routine in a background process to allow the
# X start sequence to continue. Eventually, the X server launches and xrandr
# can do its job.

(
    while ! xrandr | grep -q 'eDP-1' ; do
	sleep 0.5
    done

    xrandr --output 'eDP-1' --mode 1368x768
) &
